### ISSUE TITLE
Visual Studio 2022 v17.10.5 Breaks BDD Feature extensions

### ISSUE THREAD

**Issue by Jamie-Clayton** [reqnroll/Reqnroll#220]
### Reqnroll Version

2024.2.93

### Which test runner are you using?

xUnit

### Test Runner Version Number

NA

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

The project didn't get created properly, so I don't have one.

### Issue Description

Error hash: 78671751
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Reqnroll.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Reqnroll.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Reqnroll.VisualStudio.Package\VsUtils.cs:line 362
   at Reqnroll.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Reqnroll.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81

### Steps to Reproduce

1. New Laptop with latest developer tools just installed.
2. VS 2022 v17.10.5
3. Tried installing SpecFlow extension (errors). See [Specflow Extension issues](https://github.com/SpecFlowOSS/SpecFlow.VS/issues/171)
4. Tried Reqnroll extension (errors in a very similar way) Looks like forks of common codebase.
5. VS IDE adding a new project failes and leaves the <TargetFramework>$dotnetversion$</TargetFramework> incorrectly configured (net8.0) manually added.
6. Trying to add a specflow or reqnroll feature file causes the error activating the plugins.

**Comment by clrudolphi** [comment]
Could not reproduce after updating my VS to 17.10.5.

Please ensure that you have only one of the VS Extensions installed -- either the SpecFlow one or the Reqnroll one. Having both installed at the same time likely will result in errors.
The Reqnroll VS Extension will support SpecFlow projects, but not vice versa.

**Comment by Jamie-Clayton** [comment]
Interesting I didn't have the extentions installed and did a fresh install only once I was at 17.10.5.
Retesting with only one extension enabled.

**Comment by Jamie-Clayton** [comment]
I rolled back to 17.10.4 uninstalled a range of extensions.
Rebooted laptop.
Installed one extention at a time and yes! Everything working as expected.
