### ISSUE TITLE
Error calling binding method '...': count ('6') must be less than or equal to '0'. (Parameter 'count') Actual value was 6.

### ISSUE THREAD

**Issue by robennett3** [reqnroll/Reqnroll#304]
### Reqnroll Version

2.1.1

### Which test runner are you using?

xUnit

### Test Runner Version Number

2.9.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

This error keeps occurring; the test will work one run and then stop working and doesn't ever seem to start working again. I can usually get the test to run again by renaming the method that is mentioned in the error. Then it will stop working again.

Here is the full error:
```Reqnroll.BindingException
Error calling binding method 'Dcp.Identity.IntegrationTests:Dcp.Identity.IntegrationTests.Steps.GoogleUserStepDefinitions.GivenTheyHaveAnAccount()': count ('6') must be less than or equal to '0'. (Parameter 'count')
Actual value was 6.
   at Reqnroll.Bindings.BindingInvoker.InvokeBindingAsync(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, DurationHolder durationHolder)
   at Reqnroll.Infrastructure.TestExecutionEngine.ExecuteStepMatchAsync(BindingMatch match, Object[] arguments, DurationHolder durationHolder)
   at Reqnroll.Infrastructure.TestExecutionEngine.ExecuteStepAsync(IContextManager contextManager, StepInstance stepInstance)
   at Reqnroll.Infrastructure.TestExecutionEngine.OnAfterLastStepAsync()
   at Reqnroll.TestRunner.CollectScenarioErrorsAsync()
   at Dcp.Identity.IntegrationTests.Features.AuthenticationFeature.ScenarioCleanupAsync()
   at Dcp.Identity.IntegrationTests.Features.AuthenticationFeature.NewUserLogsInForTheFirstTime() in C:\source\dcp-identity\tests\Dcp.Identity.IntegrationTests\Features\Authentication.feature:line 14
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 259
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```

Here is the test, I have removed all parameters from the steps and I am still getting the errors.
```
Feature: Authentication
Scenario: New user logs in for the first time
Background: 
    Given a branch known as Branch1
    And the branch exists
    Given a branch known as Branch2
    And the branch exists

    Given there is a user
    And they are an Operator
    And they have the role Branch Admin
#    And they belong to the branch Branch1
#    And they belong to the branch Branch2
    And the user exists
#    When I make a call to the auth endpoint to exchange my google token
#    Then the response contains valid DCP tokens
#    And the user is created in the DCP Identity database
#    And the UserCreatedOrUpdatedEventV1 integration event has been published
```

This is the method the error is coming from:
```
    [Given("the user exists")]
    public async Task GivenTheyHaveAnAccount()
    {
        await EnsureUserHasAnAccountWithGroupsAssigned(_scenarioContext.GetCurrentUser());
        await Login(_scenarioContext.GetCurrentUser());
    }
```

### Steps to Reproduce

Not sure. Just run the tests.

**Comment by robennett3** [comment]
Good spot, I have fixed the syntax however that was not the issue. I had a unhandled exception in an asynchronous method that was called from that step. The message "count ('6') must be less than or equal to '0'. (Parameter 'count')
Actual value was 6." actually came from an out of range exception; the stack trace and the original exception type are missing from that error so it was hard to track down without stepping through the code.

**Comment by gasparnagy** [comment]
If anyone needs this, this is already supported, see https://docs.reqnroll.net/latest/integrations/mstest.html#tags-for-testclass-attributes
