### ISSUE TITLE
Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral

### ISSUE THREAD

**Issue by AhmedElbaik** [reqnroll/Reqnroll#310]
### Reqnroll Version

2.1.1

### Which test runner are you using?

xUnit

### Test Runner Version Number

2.9.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning"
    }
  },
  "specflow": {
    "bindingCulture": {
      "language": "en-us"
    },
    "language": {
      "feature": "en-us"
    },
    "stepAssemblies": [
      { "assembly": "CostbookUITestsBDD/StepDefinitions" }
    ],
    "unitTestProvider": {
      "name": "xUnit"
    }
  }
}

### Issue Description

I'm facing the below error. When I updated the Reqnroll packages to 2.1.1, When I returned back to 2.0.0, I had a succeful build to my project, I checked https://github.com/reqnroll/Reqnroll/issues/244 and https://github.com/JoshKeegan/xRetry/pull/245, which should fix the problem.
as you can see below the versions of the packages I have:-
"Reqnroll" Version="2.1.1"
"Reqnroll.CustomPlugin" Version="2.1.1"
"Reqnroll.Autofac" Version="2.1.1"
"Reqnroll.SpecFlowCompatibility" Version="2.1.1"
"Reqnroll.Tools.MsBuild.Generation" Version="2.1.1"
"Reqnroll.xUnit" Version="2.1.1"
"xRetry.Reqnroll" Version="1.0.0"
System.CodeDom" Version="8.0.0"

Also, kindly check my conversation with @JoshKeegan on the issue https://github.com/JoshKeegan/xRetry/issues/252.

Severity Code Description Project File Line Suppression State
Error (active) MSB4018 The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at xRetry.Reqnroll.GeneratorPlugin.customiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
at Reqnroll.Generator.GeneratorContainerBuilder.CreateContainer(ReqnrollConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable1 generatorPluginInfos, IObjectContainer parentObjectContainer) at Reqnroll.Tools.MsBuild.Generation.WrappedGeneratorContainerBuilder.BuildGeneratorContainer(ReqnrollConfigurationHolder reqnrollConfigurationHolder, ProjectSettings projectSettings, IReadOnlyCollection1 generatorPluginInfos, IObjectContainer rootObjectContainer)
at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTaskExecutor.Execute()
at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
CostbookUITestsBDD C:\Users\elbaika.nuget\packages\reqnroll.tools.msbuild.generation\2.1.1\build\Reqnroll.Tools.MsBuild.Generation.targets 93

### Steps to Reproduce

add "xRetry.Reqnroll" Version="1.0.0" with the below packages:
"Reqnroll" Version="2.1.1"
"Reqnroll.CustomPlugin" Version="2.1.1"
"Reqnroll.Autofac" Version="2.1.1"
"Reqnroll.SpecFlowCompatibility" Version="2.1.1"
"Reqnroll.Tools.MsBuild.Generation" Version="2.1.1"
"Reqnroll.xUnit" Version="2.1.1"
System.CodeDom" Version="8.0.0"

Then you get the mentioned error when you try to build your project.

**Comment by gasparnagy** [comment]
It is going to be included in v2.2.0 that is hopefully released tomorrow
