### ISSUE TITLE
Interface cannot be resolved: BoDi.IObjectContainer

### ISSUE THREAD

**Issue by ccarmannt** [reqnroll/Reqnroll#322]
### Reqnroll Version

2.2

### Which test runner are you using?

NUnit

### Test Runner Version Number

2.2

### .NET Implementation

.NET Framework 4.6.2 or later

### Test Execution Method

ReSharper Test Runner

### Content of reqnroll.json configuration file

None

### Issue Description

When attempting to start a test in a project newly converted from the legacy SpecFlow framework, this error is generated: Interface cannot be resolved: BoDi.IObjectContainer

The trace seems to provide no reference back to the line of test code that it came from.

Stacktrace:
```

Reqnroll.BoDi.ObjectContainerException : Interface cannot be resolved: BoDi.IObjectContainer
TearDown : Reqnroll.BoDi.ObjectContainerException : Interface cannot be resolved: BoDi.IObjectContainer
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath, TimeSpan timeout)
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Reqnroll.Infrastructure.TestExecutionEngine.<InvokeHookAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.Infrastructure.TestExecutionEngine.<OnTestRunStartAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunner.<OnTestRunStartAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunnerManager.<FireTestRunStartAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunnerManager.<OnTestRunStartAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Tests_NUnitAssemblyHooks.<AssemblyInitializeAsync>d__0.MoveNext() in obj\Debug\NUnit.AssemblyHooks.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp()
--TearDown
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath, TimeSpan timeout)
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Reqnroll.Infrastructure.TestExecutionEngine.<InvokeHookAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.Infrastructure.TestExecutionEngine.<OnTestRunEndAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunner.<OnTestRunEndAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunnerManager.<FireTestRunEndAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunnerManager.<DisposeAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reqnroll.TestRunnerManager.<OnTestRunEndAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Tests_NUnitAssemblyHooks.<AssemblyCleanupAsync>d__1.MoveNext() in obj\Debug\NUnit.AssemblyHooks.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.ValueTaskAwaitAdapter.NonGenericAdapter.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown(TestExecutionContext context)

```

### Steps to Reproduce

Not known

**Comment by gasparnagy** [comment]
Could you please retry with 2.2.1?

**Comment by ccarmannt** [comment]
I retried using 2.2.1, but the problem is unchanged.

**Comment by clrudolphi** [comment]
Would it be possible for you to post a simplified example that reproduces the problem?

**Comment by ccarmannt** [comment]
> Would it be possible for you to post a simplified example that reproduces the problem?

Possibly. I'll try to do that tomorrow.

**Comment by ccarmannt** [comment]
I tried creating a highly simplified project, but that project runs tests successfully.
I'll try again, but in the meantime, are there any ways I can attempt to debug the original project?

**Comment by clrudolphi** [comment]
Sure. You'll need to download the Reqnroll source code (or fork) from github. Build in DEBUG.
Next, remove the nuget package references to Reqnroll from your project.
Then you have two options:

1. Setup a "local" nuget source that points to {path_to_Reqnroll_source}/GeneratedNuGetPackages and then add a reference to Reqnroll.NUnit.2.2x-local (where 'x' is a digit higher than the current release#)  
2. Add a direct reference to the Reqnroll assemblies via the Add Project Reference dialog (add references to the Reqnroll.dll and Reqnroll.NUnit.ReqnrollPlugin.dll from the /Plugins/Reqnroll.NUnit.ReqnrollPllugin/bin/Debug/netstandard2.0 folder)

We're going to be interested in knowing which Hook is being executed when this error occurs and what the arguments are to the constructor of that Hook. 
The exception message being shown above is "interesting" in the head-scratching way because it is saying that the object container cannot resolve itself (which should be impossible).
Does your code modify any interface/object registrations?

**Comment by ccarmannt** [comment]
@clrudolphi here's a new stacktrace with this built configuration.

And no, I don't think we're modifying any registrations. Are there various ways to do that, or is there one easy to spot method call I can search for?

```
OneTimeSetUp: Reqnroll.BoDi.ObjectContainerException : Interface cannot be resolved: BoDi.IObjectContainer
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1() in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 148
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath, TimeSpan timeout) in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 252
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath) in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 142
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath) in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 215
   at Reqnroll.BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath) in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 629
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name) in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 547
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, String name) in C:\source\github\Reqnroll\Reqnroll\BoDi\ObjectContainer.cs:line 532
   at Reqnroll.Infrastructure.TestObjectResolver.ResolveBindingInstance(Type bindingType, IObjectContainer container) in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestObjectResolver.cs:line 10
   at Reqnroll.Infrastructure.TestExecutionEngine.ResolveArgument(IObjectContainer container, IBindingParameter parameter) in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 431
   at Reqnroll.Infrastructure.TestExecutionEngine.<>c__DisplayClass54_0.<ResolveArguments>b__0(IBindingParameter p) in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 421
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Reqnroll.Infrastructure.TestExecutionEngine.ResolveArguments(IHookBinding hookBinding, IObjectContainer currentContainer) in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 421
   at Reqnroll.Infrastructure.TestExecutionEngine.<InvokeHookAsync>d__50.MoveNext() in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 354
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext() in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext() in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 341
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Reqnroll.Infrastructure.TestExecutionEngine.<OnTestRunStartAsync>d__32.MoveNext() in C:\source\github\Reqnroll\Reqnroll\Infrastructure\TestExecutionEngine.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Reqnroll.TestRunner.<OnTestRunStartAsync>d__10.MoveNext() in C:\source\github\Reqnroll\Reqnroll\TestRunner.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Reqnroll.TestRunnerManager.<FireTestRunStartAsync>d__36.MoveNext() in C:\source\github\Reqnroll\Reqnroll\TestRunnerManager.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Reqnroll.TestRunnerManager.<OnTestRunStartAsync>d__48.MoveNext() in C:\source\github\Reqnroll\Reqnroll\TestRunnerManager.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Tests_NUnitAssemblyHooks.<AssemblyInitializeAsync>d__0.MoveNext() in C:\source\ADOS\Tools\FSF\Tests\obj\Debug\NUnit.AssemblyHooks.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp()

```

**Comment by ccarmannt** [comment]
> Have you attempted to debug into this hook method? Does the exception throw before entry into the method body? If you do get in to the method body, is the container parameter null?

Setting a breakpoint in this hook doesn't work. The debugger never starts, I presume because this hook doesn't get hit before the exception?

**Comment by ccarmannt** [comment]
> Do you have any other BeforeTestRun hooks in this solution? Any with a negative Order or where Order also equals 0? would be interested to see what they do as well.

No other BeforeTestRun hooks.

**Comment by clrudolphi** [comment]
Are you using any plugins to Reqnroll?

**Comment by ccarmannt** [comment]
No plugins.

**Comment by gasparnagy** [comment]
Oh... I think we missed the most trivial solution! I have just noticed the namespace of the unresolved interface: `BoDi.IObjectContainer`... 😎

@ccarmannt I'm pretty sure the problem is that you still have a reference to the `BoDi` package. We have merged that into the Reqnroll package, and the namespace is now `Reqnroll.BoDi` instead of `BoDi`! So make sure you remove the `BoDi` package and change all namespace usings from `BoDi` to `Reqnroll.BoDi`.

Please confirm if it helped. 🤞

**Comment by ccarmannt** [comment]
Indeed, that fixed the problem. Thank you both! @gasparnagy @clrudolphi
