### ISSUE TITLE
Reqnroll rider plugin

### ISSUE THREAD

**Issue by russog** [reqnroll/Reqnroll#327]
### Reqnroll Version

Latest

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.3

### .NET Implementation

.NET 8.0

### Test Execution Method

ReSharper Test Runner

### Issue Description

reqnroll plugin on rider 2024.3 breaks shortcuts e.g on Mac cmd+f12 does not work anymore

### Steps to Reproduce

reqnroll plugin on rider 2024.3 breaks shortcuts e.g on Mac cmd+f12 does not work anymore

**Comment by delta-emil** [comment]
I have the same problem. I have the latest version of the plugin: [2024.2.2](https://plugins.jetbrains.com/plugin/24012-reqnroll-for-rider/versions/stable/623049)

Rider version: JetBrains Rider 2024.3 Build #RD-243.21565.191, built on November 13, 2024

The Rider log file has exceptions like this:
(the look like there's a missing method that Rider now expects)

```text

10:14:40.516 |E|                               | JetPool(S) #4:18   | PartCatalogType.Bind() for [ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider, ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] failed, Container: SolutionFeaturePartCatalog Method 'SetTabOptions' in type 'ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider' from assembly 'ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

--- EXCEPTION #1/2 [TypeLoadException]
Message = “Method 'SetTabOptions' in type 'ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider' from assembly 'ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”
TypeLoadClassName = ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider
TypeLoadAssemblyName = “ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”
TypeLoadMessageArg = SetTabOptions
TypeLoadResourceID = 6012
StackTraceString = “
  at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) in ResolveType.il:line IL_0000 mvid DE3E
     at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) in ResolveTypeHandle.il:line IL_00A7 mvid DE3E
     at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) in ResolveType.il:line IL_008A mvid DE3E
     at JetBrains.Application.Table.TablePartCatalogStorage.<>c.<.cctor>b__66_1(Int32`1 tk, TablePartCatalogStorage thіs) in TablePartCatalogStorage.il:line IL_009A mvid F4FF
     at JetBrains.Application.Table.TablePartCatalogStorage.TypeBind(Int32`1 token) in TypeBind.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.NestedContainer.NestedComponentContainer.ComposeAsync() in ComposeAsync.il:line IL_00C3 mvid F4FF
”
ExceptionPath = Root.InnerException
ClassName = System.TypeLoadException
HResult = COR_E_TYPELOAD=80131522
Source = System.Private.CoreLib

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “PartCatalogType.Bind() for [ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider, ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] failed, Container: SolutionFeaturePartCatalog Method 'SetTabOptions' in type 'ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider' from assembly 'ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex) in Log.il:line IL_0024 mvid 4DEE
     at JetBrains.Diagnostics.LogEx.Error(ILog this, Exception ex, String message) in Error.il:line IL_0000 mvid 2A6A
     at JetBrains.Util.Logging.Logger.LogException(String comment, Exception ex) in LogException.il:line IL_0000 mvid 4DEE
     at JetBrains.Application.Components.NestedContainer.NestedComponentContainer.ComposeAsync() in ComposeAsync.il:line IL_00C3 mvid F4FF
     at JetBrains.Application.Components.NestedContainer.NestedComponentContainerValueResolver.NestedComponentContainerValueDescriptorBase`2..ctor(IValueResolveContext originalResolveContext, TRegisterStrategy strategy, IComponentContainer originalComponentContainer, IInitializationStrategy initializationStrategy)
     at JetBrains.Application.Components.NestedContainer.NestedComponentContainerValueResolver.NestedComponentContainerValueDescriptorHelper`2..ctor(IValueResolveContext context, IComponentContainer componentContainer, IInitializationStrategy initializationStrategy)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) in InvokeDirectByRefWithFewArgs.il:line IL_007E mvid DE3E
     at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in InvokeWithFewArgs.il:line IL_00A7 mvid DE3E
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in Invoke.il:line IL_006A mvid DE3E
     at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) in CreateInstanceImpl.il:line IL_017C mvid DE3E
     at System.Activator.CreateInstance(Type type, Object[] args) in CreateInstance.il:line IL_0000 mvid DE3E
     at JetBrains.Application.Components.NestedContainer.NestedComponentContainerValueResolver.Resolve(ResolveRequest request, ValueResolveFlags flags, IValueResolveContext context) in Resolve.il:line IL_005E mvid F4FF
     at JetBrains.Application.Components.ComponentContainer.ResolveCore(ResolveRequest request, ValueResolveFlags flags, IValueResolveContext context) in ResolveCore.il:line IL_00AE mvid F4FF
     at JetBrains.Application.Components.ComponentContainer.Resolve(ResolveRequest request, ValueResolveFlags flags, IValueResolveContext context) in Resolve.il:line IL_007F mvid F4FF
     at JetBrains.Application.Components.ComponentResolveContext.Resolve(ResolveRequest request, ValueResolveFlags flags) in Resolve.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.ValueResolveContextEx.Resolve(IValueResolveContext context, Type request, ValueResolveFlags flags) in Resolve.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.SignatureResolution.BindToMethod(MethodBase[] candidates, IValueResolveContext context, Object origin) in BindToMethod.il:line IL_0046 mvid F4FF
     at JetBrains.Application.Components.SignatureResolution.BindToConstructor(Type type, IValueResolveContext context) in BindToConstructor.il:line IL_0037 mvid F4FF
     at JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.DoGetDependenciesNoCache() in DoGetDependenciesNoCache.il:line IL_0025 mvid F4FF
     at JetBrains.Application.Components.SingletonDescriptor`1.DoGetDependenciesNoCacheValidated() in DoGetDependenciesNoCacheValidated.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.SingletonDescriptor`1.TryGetCachedDependencies(Boolean allowGetValueIfNotAlive) in TryGetCachedDependencies.il:line IL_0062 mvid F4FF
     at JetBrains.Application.Components.SingletonDescriptor`1.DoGetDependencies() in DoGetDependencies.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependenciesAsync() in GetDependenciesAsync.il:line IL_007B mvid F4FF
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_0010 mvid F4FF
     at JetBrains.Application.Components.ComponentStorage.<>c__DisplayClass26_0.<WarmUpDescriptors>g__ProcessList|4(IEnumerable`1 initialDescriptors) in ComponentStorage.il:line IL_0000 mvid F4FF or ComponentStorage.il:line IL_0039 mvid F4FF
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_00CB mvid F4FF
     at JetBrains.Application.Components.ComponentStorage.<>c__DisplayClass25_0.<ComposeDescriptors>b__0() in ComponentStorage.il:line IL_0000 mvid F4FF or ComponentStorage.il:line IL_0039 mvid F4FF
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid DE3E
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in ExecuteWithThreadLocal.il:line IL_0096 mvid DE3E
     at System.Threading.Tasks.Task.ExecuteEntry() in ExecuteEntry.il:line IL_0036 mvid DE3E
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_0014 mvid 4DEE
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0009 mvid 4DEE
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 4DEE
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 4DEE
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600

```

```text

10:14:43.616 |E| AsyncDescriptorBase           | JetPool(S) #4:18   | The component NestedComponentContainer<JetBrains.Application.Components.NestedComponentContainerAllByPartAttribute`3+NestedComponentContainerRegisterAllByPartAttributeStrategy[JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute,JetBrains.Application.Environment.ShellPartCatalogSet,JetBrains.Application.Components.NestedComponentContainerUnsafeComponentDescriptorsCreationFilter]> was created with corrupted dependencies. Could not bind the component dependency descriptor on NestedComponentContainer<JetBrains.Application.Components.NestedComponentContainerAllByPartAttribute`3+NestedComponentContainerRegisterAllByPartAttributeStrategy[JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute,JetBrains.Application.Environment.ShellPartCatalogSet,JetBrains.Application.Components.NestedComponentContainerUnsafeComponentDescriptorsCreationFilter]>. The component cannot be retrieved because its construction has failed to complete. Method 'SetTabOptions' in type 'ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider' from assembly 'ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

--- EXCEPTION #1/5 [TypeLoadException]
Message = “Method 'SetTabOptions' in type 'ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider' from assembly 'ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”
TypeLoadClassName = ReSharperPlugin.ReqnrollRiderPlugin.Navigation.ReqnrollStepOccurenceInfoProvider
TypeLoadAssemblyName = “ReSharperPlugin.ReqnrollRiderPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”
TypeLoadMessageArg = SetTabOptions
TypeLoadResourceID = 6012
StackTraceString = “
  at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) in ResolveType.il:line IL_0000 mvid DE3E
     at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) in ResolveTypeHandle.il:line IL_00A7 mvid DE3E
     at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) in ResolveType.il:line IL_008A mvid DE3E
     at JetBrains.Application.Table.TablePartCatalogStorage.<>c.<.cctor>b__66_1(Int32`1 tk, TablePartCatalogStorage thіs) in TablePartCatalogStorage.il:line IL_009A mvid F4FF
     at JetBrains.Application.Table.TablePartCatalogStorage.TypeBind(Int32`1 token) in TypeBind.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.DoGetDependenciesNoCache() in DoGetDependenciesNoCache.il:line IL_0007 mvid F4FF
     at JetBrains.Application.Components.SingletonDescriptor`1.DoGetDependenciesNoCacheValidated() in DoGetDependenciesNoCacheValidated.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.SingletonDescriptor`1.TryGetCachedDependencies(Boolean allowGetValueIfNotAlive) in TryGetCachedDependencies.il:line IL_0062 mvid F4FF
     at JetBrains.Application.Components.SingletonDescriptor`1.DoGetDependencies() in DoGetDependencies.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependenciesAsync() in GetDependenciesAsync.il:line IL_007B mvid F4FF
”
ExceptionPath = Root.InnerException.Data.BindFailures.ReqnrollStepOccurenceInfoProvider.InnerException.InnerException
ClassName = System.TypeLoadException
HResult = COR_E_TYPELOAD=80131522
Source = System.Private.CoreLib

--- Outer ---

--- EXCEPTION #2/5 [InvalidOperationException]
Message = “The component cannot be retrieved because its construction has failed to complete.”
InnerException = “Exception #1 at Root.InnerException.Data.BindFailures.ReqnrollStepOccurenceInfoProvider.InnerException.InnerException”
StackTraceString = “
  at JetBrains.Application.Components.AsyncDescriptorBase.AssertBadState() in AssertBadState.il:line IL_0011 mvid F4FF
     at JetBrains.Application.Components.AsyncDescriptorBase.ActivateAsync(Object[] dependencyValues, TaskPriority priority) in ActivateAsync.il:line IL_002E mvid F4FF
     at JetBrains.Application.Components.AsyncDescriptorBase.<>c__DisplayClass35_0.<<GetValueInParallelAsync>g__DoAsync|0>d.MoveNext() in GetValueInParallelAsync.il:line IL_0086 mvid F4FF
  --- End of stack trace from previous location ---
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.GetAsyncUnsafe(TaskPriority priority) in GetAsyncUnsafe.il:line IL_0147 mvid F4FF
”
ExceptionPath = Root.InnerException.Data.BindFailures.ReqnrollStepOccurenceInfoProvider.InnerException
ClassName = System.InvalidOperationException
HResult = COR_E_INVALIDOPERATION=80131509
Source = JetBrains.Platform.ComponentModel

--- Outer ---

--- EXCEPTION #3/5 [InvalidOperationException]
Message = “Could not bind the component dependency descriptor on NestedComponentContainer<JetBrains.Application.Components.NestedComponentContainerAllByPartAttribute`3+NestedComponentContainerRegisterAllByPartAttributeStrategy[JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute,JetBrains.Application.Environment.ShellPartCatalogSet,JetBrains.Application.Components.NestedComponentContainerUnsafeComponentDescriptorsCreationFilter]>.”
Data.ArgumentDescriptorIsAlive = False
Data.ArgumentIndex = 79
Data.Origin = NestedComponentContainer<JetBrains.Application.Components.NestedComponentContainerAllByPartAttribute`3+NestedComponentContainerRegisterAllByPartAttributeStrategy[JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute,JetBrains.Application.Environment.ShellPartCatalogSet,JetBrains.Application.Components.NestedComponentContainerUnsafeComponentDescriptorsCreationFilter]>
Data.ArgumentIsSyncMode = False
Data.ArgumentIsPrimaryThread = False
Data.ArgumentInstantiation = ContainerAsyncPrimaryThread
InnerException = “Exception #2 at Root.InnerException.Data.BindFailures.ReqnrollStepOccurenceInfoProvider.InnerException”
ExceptionPath = Root.InnerException.Data.BindFailures.ReqnrollStepOccurenceInfoProvider
ClassName = System.InvalidOperationException
HResult = COR_E_INVALIDOPERATION=80131509

--- Outer ---

--- EXCEPTION #4/5 [CorruptedDependenciesException]
Message = “The component NestedComponentContainer<JetBrains.Application.Components.NestedComponentContainerAllByPartAttribute`3+NestedComponentContainerRegisterAllByPartAttributeStrategy[JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute,JetBrains.Application.Environment.ShellPartCatalogSet,JetBrains.Application.Components.NestedComponentContainerUnsafeComponentDescriptorsCreationFilter]> was created with corrupted dependencies.”
Data.BindFailures.ReqnrollStepOccurenceInfoProvider = “Exception #3 at Root.InnerException.Data.BindFailures.ReqnrollStepOccurenceInfoProvider”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Application.Components.Descriptors.CorruptedDependenciesException
HResult = COR_E_APPLICATION=80131600

--- Outer ---

--- EXCEPTION #5/5 [LoggerException]
Message = “The component NestedComponentContainer<JetBrains.Application.Components.NestedComponentContainerAllByPartAttribute`3+NestedComponentContainerRegisterAllByPartAttributeStrategy[JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute,JetBrains.Application.Environment.ShellPartCatalogSet,JetBrains.Application.Components.NestedComponentContainerUnsafeComponentDescriptorsCreationFilter]> was created with corrupted dependencies.”
InnerException = “Exception #4 at Root.InnerException”
StackTraceString = “
  at JetBrains.Application.Components.AsyncDescriptorBase.ActivatingComponentState.TryGetSyncImpl() in TryGetSyncImpl.il:line IL_0000 mvid F4FF
     at JetBrains.Application.Components.AsyncDescriptorBase.ActivatingComponentState.GetAsyncImpl(TaskPriority priority) in GetAsyncImpl.il:line IL_0082 mvid F4FF
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid DE3E
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid DE3E
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid DE3E or MoveNext.il:line IL_0040 mvid DE3E
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid DE3E or MoveNext.il:line IL_0040 mvid DE3E
     at JetBrains.Util.Concurrency.Threading.Tasks.SchedulerAwaiter.<>c__DisplayClass11_0.<OnCompleted>b__0(Object _) in SchedulerAwaiter.il:line IL_0000 mvid 4DEE
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid DE3E
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in ExecuteWithThreadLocal.il:line IL_0096 mvid DE3E
     at System.Threading.Tasks.Task.ExecuteEntry() in ExecuteEntry.il:line IL_0036 mvid DE3E
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_0014 mvid 4DEE
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0009 mvid 4DEE
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 4DEE
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 4DEE
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
```
