### ISSUE TITLE
Gherkin.NoSuchLanguageException: 'Language not supported: en-US' when debugging

### ISSUE THREAD

**Issue by hideintheclouds** [reqnroll/Reqnroll#341]
### Reqnroll Version

2.2.1

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.2.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
  "livingDocExecutionDataCollector": {
    "enabled": true,
    "filepath": "TestExecution.json"
  },

  "language": {
    "feature": "en-US",
    "binding": "en-US"

  },

  "bindingAssemblies": [
    { "assembly": ...}
    ...
    ]
    }

### Issue Description

When running the Reqnroll test scenarios in Debug mode, there are uncaught exceptions that look like:
Exception thrown: 'Gherkin.NoSuchLanguageException' in Gherkin.dll

Gherkin.NoSuchLanguageException: 'Language not supported: en-US'
   at Gherkin.GherkinDialectProvider.GetDialect(String language, Location location)

These are thrown in the following method:
[global::NUnit.Framework.OneTimeTearDown]
[MethodImpl(MethodImplOptions.NoInlining)]
public static async ValueTask AssemblyCleanupAsync()
{
    var currentAssembly = typeof(MYPROJECT_NUnitAssemblyHooks).Assembly;
    await global::Reqnroll.TestRunnerManager.OnTestRunEndAsync(currentAssembly);
}

It seems that the Gherkin.dll is always trying to load the 'en-US' language in the GherkinDialectProvider.GetDialect() method.
Setting the language in either the feature files or reqnroll to a different value still seems to take the same default 'en-US'.

Values tried:
- en-NL
- en-UK
- en
- en-US

### Steps to Reproduce

Run the tests in debug mode in Visual Studio 2022.
The tests are executed in an air-gapped environment.
The system locale is set to en-US English (United States)
Regional Format: English (United Kingdom)

Stack trace:
at Gherkin.GherkinDialectProvider.GetDialect(String language, Location location) in Gherkin\GherkinDialectProvider.cs:line 31

**Comment by obligaron** [comment]
I have tried to reproduce the problem, but I cannot.
I can reproduce a `NoSuchLanguageException` being thrown (the debugger stops when I enable "Break when thrown" in the "Exception Settings", but it is handled.

Does this also happen with a newly created reqnroll NUnit project?
If not, could you provide a small repro where this also happens?
Does this not happen in other environments, e.g. not air-gapped?
Can you provide the full call stack when the exceptions occur (including wrapped exceptions)?

**Comment by gasparnagy** [comment]
For the record, even the handled version of the exception might be reduced now signifficantly with #336 by @obligaron. It is merged already, but not released yet.

**Comment by testgitdl** [comment]
For me this issue is reproducing. I have reqnroll version 2.2.1 and have tried to leave out the language or different combinations in the reqnroll.json but nothing worked. When debugging i get these exceptions:
1.“Gherkin.NoSuchLanguageException” in Reqnroll.dll Language not supported:en-US.
2. “Gherkin.NoSuchLanguageException” in Gherkin.dll Language not supported:en-US.
Reqnroll.json combinations tried:
- no language
- "language": {
"feature": "en-US",
"binding": "en-US"
}
- "language": {
"feature": "en-us",
"binding": "en-us"
}
- "language": {
"feature": "en",
"binding": "en"
}
- "language": {
"feature": "en-UK",
"binding": "en-UK"
}

Also for en-uk the error refferes to the same en-US

Thank you for supporting on this

**Comment by gasparnagy** [comment]
Please note that the valid English related language settings are: `en`, `en-US` and `en-GB` (there is no `en-UK`). 

@testgitdl Please note that this issue was about **unhandled** exceptions. The Gherkin parser throws and handles some exceptions internally, but this is by-design (although we would like to improve on this) and not cause an error for the end usage.

I close this issue for now, as we still could not reproduce receiving "unhandled" exceptions. Let's recheck this with the next Reqnroll version that uses Gherkin v31+.

**Comment by jeroenjanssen-cpp** [comment]
any insight in when reqnroll will support Gherkin v31+?

**Comment by 304NotModified** [comment]
I think that will be reqnroll 3.0,

See update from 30 to 32 (draft)
https://github.com/reqnroll/Reqnroll/pull/489

And

> ....
> I keep the PR as draft until we start with developing v3.0.

_Originally posted by @obligaron in https://github.com/reqnroll/Reqnroll/issues/489#issuecomment-2737916628_
